"""Edit check model: add enum field check type

Revision ID: 02a0da4bbd45
Revises: 1b1a7e20e304
Create Date: 2024-11-30 17:14:15.865415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a0da4bbd45'
down_revision: Union[str, None] = '1b1a7e20e304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('type', sa.Enum('PDF', 'URL', name='checktype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'type')
    # ### end Alembic commands ###
