"""Edit user model: edit UserRole enum and type commission

Revision ID: 39e3dc205ebd
Revises: 3a6431ddd957
Create Date: 2024-11-09 18:05:24.028514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e3dc205ebd'
down_revision: Union[str, None] = '3a6431ddd957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'PROVIDER', 'OPERATOR', 'MANAGER', 'IS_FREEZE', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('commission', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'commission')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
