"""Remove some fields from user model for edit this field in next migrate (sqlite not support alter)

Revision ID: 3a6431ddd957
Revises: a9aca2989532
Create Date: 2024-11-09 18:04:32.302035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6431ddd957'
down_revision: Union[str, None] = 'a9aca2989532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'commission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('commission', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=8), nullable=False))
    # ### end Alembic commands ###
