"""Edit Order model - add 2 fields: taking_date, close_date

Revision ID: 4a3b6140fd22
Revises: 9d88c1a7abcc
Create Date: 2024-11-25 22:30:00.275273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3b6140fd22'
down_revision: Union[str, None] = '9d88c1a7abcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('taking_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('close_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'close_date')
    op.drop_column('orders', 'taking_date')
    # ### end Alembic commands ###
