"""Edit order model: add new field - uid: str

Revision ID: 56f6c39ca7b6
Revises: 39e3dc205ebd
Create Date: 2024-11-16 15:37:34.566166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f6c39ca7b6'
down_revision: Union[str, None] = '39e3dc205ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('uid', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'uid')
    # ### end Alembic commands ###
