"""Init migration

Revision ID: 805995cc7d14
Revises: 
Create Date: 2024-11-06 19:35:01.092412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805995cc7d14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'PROVIDER', 'OPERATOR', 'MANAGER', name='userrole'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Integer(), nullable=True),
    sa.Column('provider_status', sa.Enum('NO_PROVIDER', 'INACTIVE', 'ACTIVE_INTER', 'ACTIVE_TINK', name='userproviderstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('individual_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('activate_date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.Enum('ADMIN', 'PROVIDER', 'OPERATOR', 'MANAGER', name='accesstype'), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_individual_tokens_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bank', sa.Enum('TINK', 'TINK_SBP', 'INTER', name='orderbank'), nullable=False),
    sa.Column('card', sa.String(length=16), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'CANCELLED', 'COMPLETED', 'DISPUTED', 'PROCESSING', name='orderstatus'), nullable=True),
    sa.Column('operator', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator'], ['users.id'], name='fk_orders_users_id_operator', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider'], ['users.id'], name='fk_orders_users_id_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OK', 'UNDERKPAYMENT', 'OVERPAYMENT', 'ERROR', name='checkstatus'), nullable=False),
    sa.ForeignKeyConstraint(['order'], ['orders.id'], name='fk_checks_orders_id_order', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reject_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['order'], ['orders.id'], name='fk_reject_orders_orders_id_order', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider'], ['users.id'], name='fk_reject_orders_users_id_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reject_orders')
    op.drop_table('checks')
    op.drop_table('orders')
    op.drop_table('individual_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
