"""Edit User model - remove commission float field, add commissions JSON field

Revision ID: 9d88c1a7abcc
Revises: 833417948684
Create Date: 2024-11-24 00:13:12.761984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d88c1a7abcc'
down_revision: Union[str, None] = '833417948684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('commissions', sa.JSON(none_as_null=True), nullable=True))
    op.drop_column('users', 'commission')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('commission', sa.FLOAT(), nullable=True))
    op.drop_column('users', 'commissions')
    # ### end Alembic commands ###
