"""Add url field in check model

Revision ID: a9aca2989532
Revises: 805995cc7d14
Create Date: 2024-11-06 21:45:24.684047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9aca2989532'
down_revision: Union[str, None] = '805995cc7d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('url', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'url')
    # ### end Alembic commands ###
